name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Bruteforce:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@master
    - name: Sources compilation
      run: make
    - name: Bruteforce testing
      run: make test_bruteforce
  
  Random:
    
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@master
    - name: Sources compilation
      run: make
    - name: Random testing
      run: make test_random
